---
title: "Homework 2"
author: "Joseph Elikishvili"
date: "July 22, 2016"
output: html_document
---


mychoose function takes n and r as arguments and returns nCr result using myfactorial function defined below

```{r}
mychoose = function(n,r)
{
  if(n<0 || r<=0 || n<r){
    print("Please enter positive numbers: n>=0, r>0, n>=r")
  }else 
  {
    result = myfactorial(n)/(myfactorial(r)*myfactorial(n-r))
    result
  }
}
```

myfactorial function takes a number as a argumant and returns its factorial

```{r}
myfactorial = function(x)
{
  if(x<0){
    print("Please enter positive number")
  }else 
  {
    i=1
    result=1
    while (i<=x)
    {
      result=result*i
      i=i+1
    }
    result
  }
}
```

The following tests will generate an error

```{r}
test10=mychoose(1,0)
test01=mychoose(0,1)
test1n1=mychoose(1,-1)
testn10=mychoose(-1,0)
test13=mychoose(1,3)
```

The following tests should not generate an error

```{r}
test53=mychoose(5,3)
test53
test103=mychoose(10,3)
test103
```

