---
title: "605-HW1"
author: "Joseph Elikishvili"
date: "February 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.1
u.v = 0.5x3 + 0.5x(-4) = 1.5 -2 = -0.5

## 1.2

|u| = sqrt(0.5^2 0.5^2) = sqrt(0.5) = 0.707

|v| = sqrt(3^2 + (-4)^2) = sqrt(9+16) = 5

## 1.3

3(0.5, 0.5) - 2(3, -4) = (1.5, 1.5) - (6, -8) = (-4.5, 9.5)

## 1.4

cos(Theta) = (uxv)/||v||x||v) = -0.5/0.707*5 = -0.1414

cos(Theta) = -0.1414

Theta = arccos(-0.1414) =~ 1.7127

##2.1

```{r}
A = matrix(c(1,1,3,2,-1,5,-1,-2,4),byrow=T,nrow=3,ncol=3)
B = matrix(c(1,2,6),nrow=3,ncol=1)


gauss <- function(A, B) {
  
  M = cbind(A,B)
  print(M)

  if (M[1][1] != 1)
  {
    pivot = M[1][1]
    M[1,] = M[1,]/pivot
  }
  print(M)

  pivot = M[2][1]/M[1][1]
  M[2,] = M[2,]-pivot*M[1,]
  print(M)

  pivot = M[3][1]/M[1][1]
  M[3,] = M[3,]-pivot*M[1,]
  print(M)
  
  if (M[2,2] !=0)
  {
    pivot = M[2,2]
    M[2,] = M[2,]/pivot
    print(M) 
  }
  
  pivot = M[3,2]/M[2,2]
  M[3,] = M[3,]-pivot*M[2,]
  print(M)
  
  pivot = M[3,3]
  M[3,] = M[3,]/pivot
  print(M)
  
  pivot=M[2,3]/M[3,3]
  M[2,] = M[2,] - pivot*M[3,]
  print(M)
  
  pivot=M[1,3]/M[3,3]
  M[1,] = M[1,] - pivot*M[3,]
  print(M)
  
  pivot=M[1,2]/M[2,2]
  M[1,] = M[1,] - pivot*M[2,]
  print(M)
  
  return(M)

}


M = gauss(A,B)
M[,4]
```