---
title: "JElikishvili_Assign5"
author: "Joseph Elikishvili"
date: "March 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Problem Set 1

```{r}
A = matrix(c(1,0,1,1,1,3,1,4),byrow=T,nrow=4,ncol=2)
b = matrix(c(0,8,8,20),byrow=T,nrow=4,ncol=1)

#Finding xhat
AtA = t(A) %*% A
Atb = t(A) %*% b

xhat = solve(AtA) %*% Atb
xhat

#To find error squared we can use ||A*xhat-b||^2
A %*% xhat - b

#Lets Sum the squares of above vector and we get the squared error
error_squared = 1+9+25+9
error_squared

#Instead of b = [0; 8; 8; 20], start with p = [1; 5; 13; 17] and find the exact solution
p = matrix(c(1,5,13,17),byrow=T,nrow=4,ncol=1)
Atp = t(A) %*% p
Atp
solve(AtA) %*% Atb

#Show that the error e = b ???? p = [????1; 3;????5; 3].
e=b-p
e

#Show that the error e is orthogonal to p and to each of the columns of A. We can use the fact that vectors are orthogonal if their product equals 0
t(e) %*% p

t(e) %*% A[,1]

t(e) %*% A[,2]
```

##Problem Set 2


```{r}
#Reading in the data
mpg = read.table("c:/data/auto-mpg.data")
tail(mpg)

#Extracting and preparing b and A
b = mpg$V5
sub = mpg[c(-5)]
A = data.matrix(sub, rownames.force = NA)

tail(A)


# Find the best fitting equation that expresses mpg in terms of the other 4 variables.
AtA = t(A) %*% A
Atb = t(A) %*% b

xhat = solve(AtA) %*% Atb
xhat

# calculate the fitting error between the predicted mpg of your model and the actual mpg.

e= A %*% xhat - b

esquared = e^2
error_squared = sum(esquared)
error_squared
```