---
title: "IS605-Assignment3"
author: "Joseph Elikishvili"
date: "February 19, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Problem Set 1

##### 1. What is the rank of the matrix A?

Once we perform RREF operations, we are left with 4 pivots, therefore the rank of the above matrix is 4.



##### 2. Given an mxn matrix where m > n, what can be the maximum rank? The minimum
rank, assuming that the matrix is non-zero?

The maximum rank = n
The minimum rank = 1




##### 3. What is the rank of matrix B?


Once we perform RREF operations, we are left with 1 pivot, therefore the rank for above matrix  equals 1.




#### Problem set 2
Compute the eigenvalues and eigenvectors of the matrix A. You'll need to show your
work. You'll need to write out the characteristic polynomial and show your solution.


$$\mathbf{det} \left[\begin{array}
{rrr}
1 & 2 & 3 \\
0 & 4 & 5 \\
0 & 0 & 6
\end{array}\right] -
\left[\begin{array}
{rrr}
L & 0 & 0 \\
0 & L & 0 \\
0 & 0 & L
\end{array}\right] = 0
$$


$$
\mathbf{det} \left[\begin{array}
{rrr}
1-L & 2 & 3 \\
0 & 4-L & 5 \\
0 & 0 & 6-L
\end{array}\right] = 0
$$

(1-L)[5x0 - (4-L)(6-L)] -2[0(6-L)-(0-5)] + 3[0x0-0(4-L)] =  0

 -(1-L)(4-L)(6-L) = 0 

##### Eigenvalues = 1, 4, 6



#### Finding Eigenvector for L=1

$$
\mathbf{det} \left[\begin{array}
{rrr}
1-1 & 2 & 3 \\
0 & 4-1 & 5 \\
0 & 0 & 6-1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

$$
\mathbf{det} \left[\begin{array}
{rrr}
0 & 2 & 3 \\
0 & 3 & 5 \\
0 & 0 & 5
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Performing Row operation: R3= R3*1/5

$$
\mathbf{det} \left[\begin{array}
{rrr}
0 & 2 & 3 \\
0 & 3 & 5 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Next, R2 = R2-5R3

$$
\mathbf{det} \left[\begin{array}
{rrr}
0 & 2 & 3 \\
0 & 3 & 0 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Next, R2 = R1 - 3/2R2

$$
\mathbf{det} \left[\begin{array}
{rrr}
0 & 0 & 3 \\
0 & 3 & 0 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

R1 = R1 - 3R3

$$
\mathbf{det} \left[\begin{array}
{rrr}
0 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

R2 = R2*1/3

$$
\mathbf{det} \left[\begin{array}
{rrr}
0 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Therefore we get y=0, z=0, x can be any number.  

L1 = (1,0,0)

#### Finding Eigenvector for L=4

$$
\mathbf{det} \left[\begin{array}
{rrr}
1-4 & 2 & 3 \\
0 & 4-4 & 5 \\
0 & 0 & 6-4
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

$$
\mathbf{det} \left[\begin{array}
{rrr}
-3 & 2 & 3 \\
0 &  0 & 5 \\
0 & 0 & 2
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Performing Row operations: R3 = 1/2*R3

$$
\mathbf{det} \left[\begin{array}
{rrr}
-3 & 2 & 3 \\
0 &  0 & 5 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Next, R2 = R2-5R1

$$
\mathbf{det} \left[\begin{array}
{rrr}
-3 & 2 & 3 \\
0 &  0 & 0 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Next R1 = R1-3R1

$$
\mathbf{det} \left[\begin{array}
{rrr}
-3 & 2 & 0 \\
0 &  0 & 0 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

Next -1/3*R1

$$
\mathbf{det} \left[\begin{array}
{rrr}
1 & -2/3 & 0 \\
0 &  0 & 0 \\
0 & 0 & 1
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

z = 0, x - 2/3y = 0, for y =1 x=2/3

L4 = (2/3, 1, 0)



#### Finding Eigenvector for L=6

$$
\mathbf{det} \left[\begin{array}
{rrr}
1-6 & 2 & 3 \\
0 & 4-6 & 5 \\
0 & 0 & 6-6
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

$$
\mathbf{det} \left[\begin{array}
{rrr}
-5 & 2 & 3 \\
0 &  -2 & 5 \\
0 & 0 & 0
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

R2 = -1/2*R2

$$
\mathbf{det} \left[\begin{array}
{rrr}
-5 & 2 & 3 \\
0 &  1 & -5/2 \\
0 & 0 & 0
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

R1 = R1-2R2

$$
\mathbf{det} \left[\begin{array}
{rrr}
-5 & 0 & 8 \\
0 &  1 & -5/2 \\
0 & 0 & 0
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$

R1 = -1/5*R1

$$
\mathbf{det} \left[\begin{array}
{rrr}
1 & 0 & -8/5 \\
0 &  1 & -5/2 \\
0 & 0 & 0
\end{array}\right] 
\left[\begin{array}
{rrr}
x & \\
y & \\
z 
\end{array}\right]= 0
$$


x= 8/5z, y = 5/2z, let z=1, then x = 8/5, y=5/2

L6 = (8/5,5/2,1)


#### Summary of all Eigenvalues:

L1 = (1,0,0)

L4 = (2/3, 1, 0)

L6 = (8/5,5/2,1)
