---
title: "605 - Assignment 10"
author: "Joseph Elikishvili"
date: "April 17, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Creating the matrix
A <- matrix(c(0, 1/2, 1/2, 0, 0, 0, 
              1/6, 1/6, 1/6, 1/6, 1/6, 1/6, 
              1/3, 1/3, 0, 0, 1/3, 0,
              0, 0, 0, 0, 1/2, 1/2, 
              0, 0, 0, 1/2, 0, 1/2,
              0, 0, 0, 1, 0, 0), nrow=6, byrow = TRUE)
A
```

```{r}
#Applying the decay
B = 0.85*A + 0.15/6
B
```

```{r}
r = c(1/6, 1/6, 1/6, 1/6, 1/6, 1/6)


#Trying n=50
for (n in 1:50) {
  r = r%*%B
}

print (r)


#50 seems to be a safe number where teh values converge
for (n in 1:100) {
  r = r%*%B
}

print (r)

```

```{r}
eigen(t(B))
#We got the eigenvalue of 1 that happens to be the largest value.


# First Eigenvector seems to be similar to our vector multiplied by 2
eigen(t(B))$vectors[,1]/2
```



```{r}
library(igraph)
# Recreting matrix with proper second row
A <- matrix(c(0, 1/2, 1/2, 0, 0, 0, 
              0, 0, 0, 0, 0, 0, 
              1/3, 1/3, 0, 0, 1/3, 0,
              0, 0, 0, 0, 1/2, 1/2, 
              0, 0, 0, 1/2, 0, 1/2,
              0, 0, 0, 1, 0, 0), nrow=6, byrow = TRUE)
p = graph_from_adjacency_matrix(A, weighted=TRUE)

plot(p)

#The page_rank function gives us the same vector
page_rank(p)

```