---
title: "IS605 Assignment 9"
author: "Joseph Elikishvili"
date: "April 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



##Q1.
```{r}

f1 = function(x) 
{
  if (x >=0 && x <=1) 
  {
    return(x)
  }
  
  if (x>1 && x<=2) 
  {
    return(2-x)
  }
  
}

# Using Inverse Transform method, First we integrate and then find the inverse of the function
f11 = function(x)
{
  if (x<=0.5)
  {
    return(sqrt(2*x))
  }
  else
  {
    return(2-sqrt(2*(1-x)))
  }
}

f1(0.9)
f1(1.2)
f11(0.9)
f11(1.2)
```


##Q2.
```{r}
f2 = function(x) 
{
  if (x >=0 && x <=1)
  {
    return(1-x)
  }
  
  if (x>1 && x<=2) 
  {
    return(x-1)
  }
  
}

f22 = function(x)
{
  if (x < 0.5)
  {
    return (1-sqrt(1-2*x))
  }
  else
  {
    return (1+sqrt(2*x-1))
  }
}


f2(0.9)
f2(1.2)
f22(0.9)
f22(1.2)
```

## Q3.

```{r}

pop1 = seq(0,1,by=0.002)

v1 = sapply(pop1, f11)
v2 = sapply(pop1, f22)

s1 = sample(v1,1000, replace=TRUE, prob= NULL)
s2 = sample(v2,1000, replace=TRUE, prob= NULL)

library(ggplot2)
qplot(s1)
qplot(s2)
```

## Q4.

```{r}
fn1 = function(n, pdf)
{
  vn = vector()
  vmean = vector()
  for (j in 1:1000)
  {
    
      if (pdf == 'f1')
      {
        v1 = sample(sapply(pop1, f11),1000, replace=TRUE, prob= NULL)
        
      }
      if (pdf == 'f2')
      {
        v1 = sample(sapply(pop1, f22),1000, replace=TRUE, prob= NULL)
      }
    
    vmean <- c(vmean,mean(v1))
  }
  hist(vmean)
  return(mean(vmean))
}

fn1(20,'f1')

fn1(20,'f2')

```

## Q5

```{r}
fn1(10,'f1')

fn1(10,'f2')

fn1(30,'f1')

fn1(30,'f2')
```